apiVersion: v1
kind: ServiceAccount
metadata:
  name: clean-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clean-operator-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clean-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clean-operator-role
subjects:
- kind: ServiceAccount
  name: clean-operator-sa
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-operator
  template:
    metadata:
      labels:
        app: clean-operator
    spec:
      serviceAccountName: clean-operator-sa
      containers:
      - name: clean-operator
        image: acilot/k8s-cleaner-operator:latest
        imagePullPolicy: Always