apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-cleanup-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-cleanup-operator
  template:
    metadata:
      labels:
        app: pod-cleanup-operator
    spec:
      serviceAccountName: pod-cleanup-operator
      automountServiceAccountToken: true
      containers:
        - name: operator
          image: your-docker-repo/pod-cleanup-operator:latest
          imagePullPolicy: Always
          env:
            - name: NAMESPACE_PATTERNS
              value: "std-.*"
            - name: NAMESPACE_LIST
              value: ""
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
