name: Build and Deploy k8s-cleaner-operator

on:
  push:
    branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: acilot/k8s-cleaner-operator
  DOCKER_REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version/tag
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            VERSION="latest"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Get kubernetes auth
        env:
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yandex-cloud -n
          /opt/yandex-cloud/bin/yc config set token $YC_TOKEN
          /opt/yandex-cloud/bin/yc config set folder-id b1g0fte6g0ekfau94nhb
          /opt/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials infra-k8s --external

      - name: Set image in manifests
        run: |
          sed -i "s|image:.*|image: acilot/k8s-cleaner-operator:${{ steps.get_version.outputs.VERSION }}|" k8s/deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/rbac.yaml
          kubectl apply -f k8s/deployment.yaml
